--SELECT ALL TABLES IN DATABASE
SELECT owner, table_name
FROM all_tables
WHERE owner = 'CHERRERA2018';

--CREATE LOGIN TABLE
CREATE TABLE login
(USER_ID INT NOT NULL,
USERNAME VARCHAR2(30) NOT NULL ,
PASSWORD VARCHAR2(30) NOT NULL);

--INSERT VALUES INTO LOGIN TABLE
INSERT INTO login (USER_ID, USERNAME, PASSWORD)
VALUES (1234, 'admin', 'Password');
